### ISSUE TITLE
Mobile view?

### ISSUE THREAD

**Issue by kanlukasz** [piecioshka/vanilla-lightbox.js#5]
FF latest verion (mobile view)

![39441415_445395562620688_4778643401656500224_n](https://user-images.githubusercontent.com/30685349/44297296-4dae5200-a2cf-11e8-9360-0846220bb732.jpg)

**Comment by piecioshka** [comment]
@kanlukasz hey!

Can you check this branch: https://github.com/piecioshka/vanilla-lightbox.js/pull/6 ?

**Comment by kanlukasz** [comment]
It's been a long time, and now I can not test it because the project is no longer maintained. Sorry about that. I hope you can test it and implement it yourself. I close ticket due to unable test

**Comment by piecioshka** [comment]
Ok, thanks @kanlukasz. I will merge #6 - I'm happy to wrote that code 😄
